[package]
name = "polkadot-node-core-proposer"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.4"
futures-timer = "3.0.2"
log = "0.4.8"
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-overseer = { path = "../../overseer" }
polkadot-primitives = { path = "../../../primitives" }
sc-basic-authorship = { git = "https://github.com/tomaka/polkadot", branch = "fix-7074" }
sc-block-builder = { git = "https://github.com/tomaka/polkadot", branch = "fix-7074" }
sc-client-api = { git = "https://github.com/tomaka/polkadot", branch = "fix-7074" }
sp-api = { git = "https://github.com/tomaka/polkadot", branch = "fix-7074" }
sp-blockchain = { git = "https://github.com/tomaka/polkadot", branch = "fix-7074" }
sp-consensus = { git = "https://github.com/tomaka/polkadot", branch = "fix-7074" }
sp-core = { git = "https://github.com/tomaka/polkadot", branch = "fix-7074" }
sp-inherents = { git = "https://github.com/tomaka/polkadot", branch = "fix-7074" }
sp-runtime = { git = "https://github.com/tomaka/polkadot", branch = "fix-7074" }
sp-transaction-pool = { git = "https://github.com/tomaka/polkadot", branch = "fix-7074" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", git = "https://github.com/tomaka/polkadot", branch = "fix-7074" }
